AH:
  standard_units: g/m^3
  long_name: Absolute humidity
  standard_name: mass_concentration_of_water_vapor_in_air
  plausible_min: 0.0
  plausible_max: 50.0
AH_IRGA:
  standard_units: g/m^3
  long_name: Absolute humidity
  standard_name: mass_concentration_of_water_vapor_in_air
  plausible_min: 0.0
  plausible_max: 50.0
AH_IRGA_Av:
  standard_units: g/m^3
  long_name: Absolute humidity
  standard_name: mass_concentration_of_water_vapor_in_air
  plausible_min: 0.0
  plausible_max: 50.0
AH_IRGA_Sd:
  standard_units: g/m^3
  long_name: Absolute humidity
  standard_name: nan
  plausible_min: 0.0
  plausible_max: ''
AH_IRGA_Vr:
  standard_units: g^2/m^6
  long_name: Absolute humidity
  standard_name: nan
  plausible_min: 0.0
  plausible_max: ''
CO2:
  standard_units: umol/mol
  long_name: CO2 mole fraction
  standard_name: mole_fraction_of_carbon_dioxide_in_air
  plausible_min: 350.0
  plausible_max: 1500.0
CO2_IRGA:
  standard_units: umol/mol
  long_name: CO2 mole fraction
  standard_name: mole_fraction_of_carbon_dioxide_in_air
  plausible_min: 350.0
  plausible_max: 1500.0
CO2_IRGA_Av:
  standard_units: umol/mol
  long_name: CO2 mole fraction
  standard_name: mole_fraction_of_carbon_dioxide_in_air
  plausible_min: 350.0
  plausible_max: 1500.0
CO2_IRGA_Sd:
  standard_units: umol/mol
  long_name: CO2 mole fraction
  standard_name: mole_fraction_of_carbon_dioxide_in_air
  plausible_min: 350.0
  plausible_max: 1500.0
CO2_IRGA_Vr:
  standard_units: umol/mol
  long_name: CO2 mole fraction
  standard_name: mole_fraction_of_carbon_dioxide_in_air
  plausible_min: 350.0
  plausible_max: 1500.0
CO2c_IRGA:
  standard_units: mg/m^3
  long_name: CO2 concentration
  standard_name: mass_concentration_of_carbon_dioxide_in_air
  plausible_min: 400.0
  plausible_max: 1600.0
EC:
  standard_units: dS/m
  long_name: Electrical conductivity (soil)
  standard_name: nan
  plausible_min: ''
  plausible_max: ''
ER:
  standard_units: umol/m^2/s
  long_name: Ecosystem respiration
  standard_name: nan
  plausible_min: 0.0
  plausible_max: 30.0
ET:
  standard_units: mm
  long_name: Evapotranspiration
  standard_name: nan
  plausible_min: ''
  plausible_max: ''
Fa:
  standard_units: W/m^2
  long_name: Available energy
  standard_name: nan
  plausible_min: -300.0
  plausible_max: 1000.0
Fco2:
  standard_units: umol/m^2/s
  long_name: CO2 flux
  standard_name: surface_upward_mole_flux_of_carbon_dioxide
  plausible_min: -50.0
  plausible_max: 30.0
Fe:
  standard_units: W/m^2
  long_name: Latent heat flux
  standard_name: surface_upward_latent_heat_flux
  plausible_min: -200.0
  plausible_max: 1000.0
Fg:
  standard_units: W/m^2
  long_name: Ground heat flux
  standard_name: downward_heat_flux_at_ground_level_in_soil
  plausible_min: -200.0
  plausible_max: 200.0
Fh:
  standard_units: W/m^2
  long_name: Sensible heat flux
  standard_name: surface_upward_sensible_heat_flux
  plausible_min: -200.0
  plausible_max: 1000.0
Fld:
  standard_units: W/m^2
  long_name: Down-welling longwave
  standard_name: surface_downwelling_longwave_flux_in_air
  plausible_min: 100.0
  plausible_max: 600.0
Flu:
  standard_units: W/m^2
  long_name: Up-welling longwave
  standard_name: surface_upwelling_longwave_flux_in_air
  plausible_min: 100.0
  plausible_max: 700.0
Fm:
  standard_units: kg/m/s^2
  long_name: Momentum flux
  standard_name: magnitude_of_surface_downward_stress
  plausible_min: ''
  plausible_max: ''
Fn:
  standard_units: W/m^2
  long_name: Net radiation
  standard_name: surface_net_downward_radiative_flux
  plausible_min: -300.0
  plausible_max: 1000.0
Fsd:
  standard_units: W/m^2
  long_name: Down-welling shortwave
  standard_name: surface_downwelling_shortwave_flux_in_air
  plausible_min: -20.0
  plausible_max: 1412.0
Fsu:
  standard_units: W/m^2
  long_name: Up-welling shortwave
  standard_name: surface_upwelling_shortwave_flux_in_air
  plausible_min: -20.0
  plausible_max: 1412.0
GPP:
  standard_units: umol/m^2/s
  long_name: Gross primary productivity
  standard_name: nan
  plausible_min: -60.0
  plausible_max: 0.0
H2O:
  standard_units: mmol/mol
  long_name: H2O concentration
  standard_name: mole_fraction_of_water_vapor_in_air
  plausible_min: 80.0
  plausible_max: 0.0
L:
  standard_units: m
  long_name: Monin-Obukhov length
  standard_name: nan
  plausible_min: ''
  plausible_max: ''
NEE:
  standard_units: umol/m^2/s
  long_name: Net ecosystem exchange
  standard_name: nan
  plausible_min: -50.0
  plausible_max: 30.0
NEP:
  standard_units: umol/m^2/s
  long_name: Net ecosystem productivity
  standard_name: nan
  plausible_min: -50.0
  plausible_max: 30.0
PAR:
  standard_units: umol/m^2/s
  long_name: Photosynthetically active radiation
  standard_name: surface_downwelling_photosynthetic_photon_flux_in_air
  plausible_min: ''
  plausible_max: ''
Precip:
  standard_units: mm
  long_name: Rainfall
  standard_name: thickness_of_rainfall_amount
  plausible_min: 0.0
  plausible_max: 100.0
RH:
  standard_units: percent
  long_name: Relative humidity
  standard_name: relative_humidity
  plausible_min: 0.0
  plausible_max: 100.0
Sco2:
  standard_units: umol/m^2/s
  long_name: CO2 flux (storage)
  standard_name: nan
  plausible_min: ''
  plausible_max: ''
SH:
  standard_units: kg/kg
  long_name: Specific humidity
  standard_name: specific_humidity
  plausible_min: ''
  plausible_max: ''
SHD:
  standard_units: kg/kg
  long_name: Specific humidity deficit
  standard_name: nan
  plausible_min: ''
  plausible_max: ''
Sws:
  standard_units: m^3/m^3
  long_name: Soil water content
  standard_name: volume_fraction_of_condensed_water_in_soil
  plausible_min: 0.0
  plausible_max: 100.0
Ta:
  standard_units: degC
  long_name: Air temperature
  standard_name: air_temperature
  plausible_min: -40.0
  plausible_max: 60.0
Ts:
  standard_units: degC
  long_name: Soil temperature
  standard_name: soil_temperature
  plausible_min: -40.0
  plausible_max: 80.0
Td:
  standard_units: degC
  long_name: Dew point temperature
  standard_name: dew_point_temperature
  plausible_min: -65.0
  plausible_max: 40.0
Tv_SONIC:
  standard_units: degC
  long_name: Virtual temperature
  standard_name: virtual_temperature
  plausible_min: -40.0
  plausible_max: 60.0
Tv_SONIC_Av:
  standard_units: degC
  long_name: Virtual temperature
  standard_name: virtual_temperature
  plausible_min: -40.0
  plausible_max: 60.0
Tv_SONIC_Sd:
  standard_units: degC
  long_name: Virtual temperature
  standard_name: virtual_temperature
  plausible_min: ''
  plausible_max: ''
Tv_SONIC_Vr:
  standard_units: degC^2
  long_name: Virtual temperature
  standard_name: virtual_temperature
  plausible_min: ''
  plausible_max: ''
Tcanopy:
  standard_units: degC
  long_name: Canopy temperature
  standard_name: nan
  plausible_min: -40.0
  plausible_max: 60.0
Tbody_RAD:
  standard_units: K
  long_name: Radiometer body temperature
  standard_name: nan
  plausible_min: 233.0
  plausible_max: 333.0
Tpanel:
  standard_units: degC
  long_name: Logger panel temperature
  standard_name: nan
  plausible_min: -40.0
  plausible_max: 60.0
U:
  standard_units: m/s
  long_name: Wind speed, east component
  standard_name: eastward_wind
  plausible_min: ''
  plausible_max: ''
V:
  standard_units: m/s
  long_name: Wind speed, north component
  standard_name: northward_wind
  plausible_min: ''
  plausible_max: ''
VP:
  standard_units: kPa
  long_name: Vapour pressure
  standard_name: water_vapor_partial_pressure_in_air
  plausible_min: ''
  plausible_max: ''
VPD:
  standard_units: kPa
  long_name: Vapour pressure deficit
  standard_name: water_vapor_saturation_deficit_in_air
  plausible_min: ''
  plausible_max: ''
W:
  standard_units: m/s
  long_name: Wind speed, vertical component
  standard_name: nan
  plausible_min: ''
  plausible_max: ''
Wd:
  standard_units: degrees
  long_name: Wind direction
  standard_name: wind_from_direction
  plausible_min: 0.0
  plausible_max: 360.0
Ws:
  standard_units: m/s
  long_name: Wind speed
  standard_name: wind_speed
  plausible_min: 0.0
  plausible_max: 60.0
Wd_SONIC:
  standard_units: degrees
  long_name: Wind direction
  standard_name: wind_from_direction
  plausible_min: 0.0
  plausible_max: 360.0
Ws_SONIC:
  standard_units: m/s
  long_name: Wind speed
  standard_name: wind_speed
  plausible_min: 0.0
  plausible_max: 60.0
ps:
  standard_units: kPa
  long_name: Surface air pressure
  standard_name: surface_air_pressure
  plausible_min: 50.0
  plausible_max: 110.0
Vbat:
  standard_units: V
  long_name: Battery voltage
  standard_name: nan
  plausible_min: ''
  plausible_max: ''
time:
  standard_units: days since 1800-01-01 00:00:00.0
  long_name: time
  standard_name: time
  plausible_min: ''
  plausible_max: ''
ustar:
  standard_units: m/s
  long_name: Friction velocity
  standard_name: nan
  plausible_min: 0.0
  plausible_max: 5.0
AGC_IRGA:
  standard_units: percent
  long_name: IRGA automatic gain control value
  standard_name: nan
  plausible_min: 0.0
  plausible_max: 100.0
Diag_IRGA:
  standard_units: '1'
  long_name: IRGA diagnostic value
  standard_name: nan
  plausible_min: 0.0
  plausible_max: 36000.0
Diag_SONIC:
  standard_units: '1'
  long_name: Sonic diagnostic value
  standard_name: nan
  plausible_min: 0.0
  plausible_max: 36000.0
CO2Sig_IRGA:
  standard_units: percent
  long_name: CO2 signal strength
  standard_name: nan
  plausible_min: 0.0
  plausible_max: 102.5
H2OSig_IRGA:
  standard_units: percent
  long_name: H2O signal strength
  standard_name: nan
  plausible_min: 0.0
  plausible_max: 102.5
Sig_IRGA:
  standard_units: percent
  long_name: Signal strength
  standard_name: nan
  plausible_min: 0.0
  plausible_max: 102.5
UxA:
  standard_units: g/m^2/s
  long_name: Covariance of Ux and H2O
  standard_name: nan
  plausible_min: ''
  plausible_max: ''
UxC:
  standard_units: mg/m^2/s
  long_name: Covariance of Ux and CO2
  standard_name: nan
  plausible_min: ''
  plausible_max: ''
UxT:
  standard_units: m.degC/s
  long_name: Covariance of Ux and T
  standard_name: nan
  plausible_min: ''
  plausible_max: ''
UxUy:
  standard_units: m^2/s^2
  long_name: Covariance of Ux and Uy
  standard_name: nan
  plausible_min: ''
  plausible_max: ''
UxUz:
  standard_units: m^2/s^2
  long_name: Covariance of Ux and Uz
  standard_name: nan
  plausible_min: ''
  plausible_max: ''
Ux_SONIC:
  standard_units: m/s
  long_name: Longitudinal wind velocity component, sonic coordinates
  standard_name: nan
  plausible_min: ''
  plausible_max: ''
Ux_SONIC_Av:
  standard_units: m/s
  long_name: Longitudinal wind velocity component, sonic coordinates
  standard_name: nan
  plausible_min: ''
  plausible_max: ''
Ux_SONIC_Sd:
  standard_units: m/s
  long_name: Longitudinal wind velocity component, sonic coordinates
  standard_name: nan
  plausible_min: ''
  plausible_max: ''
Ux_SONIC_Vr:
  standard_units: m^2/s^2
  long_name: Longitudinal wind velocity component, sonic coordinates
  standard_name: nan
  plausible_min: ''
  plausible_max: ''
UyA:
  standard_units: g/m^2/s
  long_name: Covariance of Uy and H2O
  standard_name: nan
  plausible_min: ''
  plausible_max: ''
UyC:
  standard_units: mg/m^2/s
  long_name: Covariance of Uy and CO2
  standard_name: nan
  plausible_min: ''
  plausible_max: ''
UyT:
  standard_units: m.degC/s
  long_name: Covariance of Uy and T
  standard_name: nan
  plausible_min: ''
  plausible_max: ''
UyUz:
  standard_units: m^2/s^2
  long_name: Covariance of Uy and Uz
  standard_name: nan
  plausible_min: ''
  plausible_max: ''
Uy_SONIC:
  standard_units: m/s
  long_name: Lateral wind velocity component, sonic coordinates
  standard_name: nan
  plausible_min: ''
  plausible_max: ''
Uy_SONIC_Av:
  standard_units: m/s
  long_name: Lateral wind velocity component, sonic coordinates
  standard_name: nan
  plausible_min: ''
  plausible_max: ''
Uy_SONIC_Sd:
  standard_units: m/s
  long_name: Lateral wind velocity component, sonic coordinates
  standard_name: nan
  plausible_min: ''
  plausible_max: ''
Uy_SONIC_Vr:
  standard_units: m^2/s^2
  long_name: Lateral wind velocity component, sonic coordinates
  standard_name: nan
  plausible_min: ''
  plausible_max: ''
UzA:
  standard_units: g/m^2/s
  long_name: Covariance of Uz and H2O
  standard_name: nan
  plausible_min: ''
  plausible_max: ''
UzC:
  standard_units: mg/m^2/s
  long_name: Covariance of Uz and CO2
  standard_name: nan
  plausible_min: ''
  plausible_max: ''
UzT:
  standard_units: m.degC/s
  long_name: Covariance of Uz and T
  standard_name: nan
  plausible_min: ''
  plausible_max: ''
Uz_SONIC:
  standard_units: m/s
  long_name: Vertical wind velocity component, sonic coordinates
  standard_name: nan
  plausible_min: ''
  plausible_max: ''
Uz_SONIC_Av:
  standard_units: m/s
  long_name: Vertical wind velocity component, sonic coordinates
  standard_name: nan
  plausible_min: ''
  plausible_max: ''
Uz_SONIC_Sd:
  standard_units: m/s
  long_name: Vertical wind velocity component, sonic coordinates
  standard_name: nan
  plausible_min: ''
  plausible_max: ''
Uz_SONIC_Vr:
  standard_units: m/s
  long_name: Vertical wind velocity component, sonic coordinates
  standard_name: nan
  plausible_min: ''
  plausible_max: ''
FAPAR:
  standard_units: frac
  long_name: Fraction of incident photosynthetically active radiation absorbed
  standard_name: nan
  plausible_min: ''
  plausible_max: ''
APAR:
  standard_units: umol/m^2/s
  long_name: Incident photosynthetically active radiation absorbed
  standard_name: nan
  plausible_min: ''
  plausible_max: ''
