AliceSpringsMulga:
  soil_heat_flux: Fg_8cma, Fg_8cmb, Fg_8cmc
  soil_temperature: Ts_2-6cma, Ts_2-6cmb, Ts_2-6cmc
  soil_moisture: Sws_0-10cma, Sws_0-10cmb, Sws_0-10cmc
Boyagin:
  soil_heat_flux: Fg_8cma, Fg_8cmb
  soil_temperature: Ts_05cmb1, Ts_10cmb1, Ts_20cmb1, Ts_40cmb, Ts_80cmb
  soil_moisture: Sws_05cmb1, Sws_10cmb1, Sws_20cmb1, Sws_40cmb, Sws_80cmb
Calperum:
  soil_heat_flux: Fg_8cma, Fg_8cmb, Fg_8cmc
  soil_temperature: Ts_8cma, Ts_8cmb, Ts_8cmc
  soil_moisture: Sws_10cma, Sws_10cmb, Sws_10cmc
Dookie1:
  soil_heat_flux: Fg_16cma
  soil_temperature: Ts_2-16cma
  soil_moisture: Sws_18cma, Sws_18cmb
Fletcherview:
  soil_heat_flux: Fg_8cma, Fg_8cmb, Fg_8cmc, Fg_8cmd
  soil_temperature: Ts_2-6cma, Ts_2-6cmb, Ts_2-6cmc, Ts_2-6cmd
  soil_moisture: Sws_0-10cma, Sws_0-10cmb, Sws_0-10cmc, Sws_0-10cmd
Gingin:
  soil_heat_flux: Fg_8cma, Fg_8cmb, Fg_8cmc, Fg_8cmd
  soil_temperature: Ts_4cma, Ts_4cmb, Ts_4cmc, Ts_4cmd
  soil_moisture: Sws_10cma, Sws_20cma, Sws_40cma, Sws_80cma, Sws_160cma
GreatWesternWoodlands:
  soil_heat_flux: Fg_8cma, Fg_8cmb, Fg_8cmc
  soil_temperature: Ts_10cma, Ts_10cmb
  soil_moisture: Sws_5cma, Sws_10cma, Sws_30cma, Sws_50cma, Sws_70cma, Sws_110cma
Litchfield:
  soil_heat_flux: Fg_8cma, Fg_8cmb
  soil_temperature: Ts_5cmb, Ts_20cmb, Ts_50cmb, Ts_100cmb, Ts_140cmb
  soil_moisture: Sws_5cmb, Sws_20cmb, Sws_50cmb, Sws_100cmb, Sws_140cmb
MyallValeA:
  soil_heat_flux: Fg_16cma, Fg_16cmb, Fg_16cmc
  soil_temperature: Ts_8cma, Ts_8cmb, Ts_8cmc
  soil_moisture: Sws_8cma, Sws_8cmb, Sws_8cmc
MyallValeB:
  soil_heat_flux: Fg_16cma, Fg_16cmb, Fg_16cmc
  soil_temperature: Ts_8cma, Ts_8cmb, Ts_8cmc
  soil_moisture: Sws_8cma, Sws_8cmb, Sws_8cmc
SilverPlains:
  soil_heat_flux: Fg_8cma, Fg_8cmb, Fg_8cmc
  soil_temperature: Ts_10cma, Ts_10cmb, Ts_10cmc, Ts_30cma
  soil_moisture: Sws_10cma, Sws_10cmb, Sws_10cmc, Sws_30cma
TiTreeEast:
  soil_heat_flux: Fg_16cma
  soil_temperature: Ts_10cma
  soil_moisture: Sws_10cma, Sws_35cma, Sws_60cma, Sws_85cma
Tumbarumba:
  soil_heat_flux: Fg_16cma, Fg_16cmb
  soil_temperature: Ts_2-16cma, Ts_2-16cmb
  soil_moisture: Sws_0-30cma, Sws_50cma, Sws_70cma, Sws_110-140cma
Whroo:
  soil_heat_flux: Fg_8cma, Fg_8cmb, Fg_8cmd
  soil_temperature: Ts_8cma, Ts_8cmb, Ts_8cmc, Ts_8cmd
  soil_moisture: Sws_5cme, Sws_10cme, Sws_20cme, Sws_40cme, Sws_75cme, Sws_100cme
WombatStateForest:
  soil_heat_flux: Fg_13cma, Fg_16cmb
  soil_temperature: Ts_5-18cma, Ts_5-18cmb
  soil_moisture: Sws_10cma, Sws_20cma, Sws_40cma, Sws_60cma