AliceSpringsMulga: 1
AlpinePeat: 65
Boyagin: 2
Calperum: 3
CumberlandPlain: 4
Dookie1: 63
Dookie2: 66
Dookie3: 67
Fletcherview: 13
Gingin: 5
GreatWesternWoodlands: 6
HowardSprings: 54
Litchfield: 7
Longreach: 8
MyallValeA: 61
MyallValeB: 62
Ridgefield: 57
RobsonCreek: 9
SilverPlains: 53
SnowGum: 55
SturtPlains: 56
TiTreeEast: 52
Tumbarumba: 10
Wedgetail: 64
Warra: 11
Wellington: 59
Whroo: 14
WombatStateForest: 12
Yanco: 58
