AliceSpringsMulga:
  id: https://w3id.org/tern/resources/fd2809a2-e705-4961-b09c-7e9ae1ffa87e
  fluxnet_id: AU-ASM
  date_commissioned: '2010-09-01'
  latitude: -22.2828
  longitude: 133.2493
  elevation: 606.0
  time_step: 30
  freq_hz: 10
  canopy_height: 6.5
  soil: red kandosol, sandy loam
  tower_height: 13.7
  vegetation: 'Canopy + three types of understorey (vegetation1-4). vegetation1: Mulga
    canopy: Acacia aneura and A. aptaneura; vegetation2: C3 understorey forbs and
    shrubs: Psydrax latifolia, Eremophila gilesii, E. latrobei ssp glabra (Crimson
    turkey bush), Sida and Abutilon spp, and Solanum ellipticum (Potato bush); vegetation3:
    C3 understorey grass: perennial Thyridolepsis mitchelliana (Window mulga-grass);
    vegetation4: C4 understorey grasses: perennial Eragrostis eriopoda (Naked woolybutt)
    and annual Eriachne pulchella ssp pulchella (Pretty wanderrie).'
  time_zone: Australia/Darwin
  UTC_offset: 9.5
AlpinePeat:
  id: https://w3id.org/tern/resources/77df3c32-a853-4bed-ad13-192c639288c8
  fluxnet_id: AU-APL
  date_commissioned: '2017-04-01'
  latitude: -36.861
  longitude: 147.321
  elevation: 1650.0
  time_step: 30
  freq_hz: 10
  canopy_height: 0.3
  soil: null
  tower_height: 2.2
  vegetation: null
  time_zone: Australia/Melbourne
  UTC_offset: 10.0
SnowGum:
  id: https://w3id.org/tern/resources/7b99bea8-eb8f-43e2-9726-919728120678
  fluxnet_id: AU-SNO
  date_commissioned: '2023-12-01'
  latitude: -36.3715
  longitude: 148.432
  elevation: 1616.0
  time_step: 30
  freq_hz: 10
  canopy_height: null
  soil: null
  tower_height: null
  vegetation: null
  time_zone: Australia/Sydney
  UTC_offset: 10.0
BeaconFarm:
  id: https://w3id.org/tern/resources/d8c5ad2e-8b31-46c6-b802-c060f3ff1ded
  fluxnet_id: NZ-Bfm
  date_commissioned: '2012-01-01'
  latitude: -43.593
  longitude: 171.928
  elevation: null
  time_step: null
  freq_hz: null
  canopy_height: null
  soil: null
  tower_height: null
  vegetation: null
  time_zone: Pacific/Auckland
  UTC_offset: 12.0
Boyagin:
  id: https://w3id.org/tern/resources/5c711072-4336-4f70-a51d-c16e13d06f9c
  fluxnet_id: AU-Boy
  date_commissioned: '2017-09-01'
  latitude: -32.477093
  longitude: 116.938559
  elevation: 484.0
  time_step: 30
  freq_hz: 10
  canopy_height: 13.0
  soil: null
  tower_height: 30.0
  vegetation: Dry sclerophyll woodland
  time_zone: Australia/Perth
  UTC_offset: 8.0
Calperum:
  id: https://w3id.org/tern/resources/944be073-1ac3-4b3f-affb-080c7c08af5e
  fluxnet_id: AU-Cpr
  date_commissioned: '2010-07-01'
  latitude: -34.0027
  longitude: 140.5877
  elevation: 60.0
  time_step: 30
  freq_hz: 10
  canopy_height: 3.0
  soil: Reddish brown, yellowish red, loamy sand, free grain structure; low organic
    matter, loose consistence; pH 6
  tower_height: 20.0
  vegetation: Mallee
  time_zone: Australia/Adelaide
  UTC_offset: 9.5
CowBay:
  id: https://w3id.org/tern/resources/5eeb3010-59ad-4c6a-9fa6-388438199c53
  fluxnet_id: AU-Cow
  date_commissioned: '2008-12-01'
  latitude: -16.238189
  longitude: 145.42715
  elevation: 86.0
  time_step: 30
  freq_hz: 10
  canopy_height: 26.0
  soil: red clay loam podzolic soils
  tower_height: 35.0
  vegetation: lowland complex mesophyll vine forest
  time_zone: Australia/Brisbane
  UTC_offset: 10.0
CumberlandPlain:
  id: https://w3id.org/tern/resources/f6ec7f3f-bbeb-4f8f-9fba-a74aec2e1769
  fluxnet_id: AU-Cum
  date_commissioned: '2012-09-01'
  latitude: -33.6152
  longitude: 150.7236
  elevation: 20.0
  time_step: 30
  freq_hz: 10
  canopy_height: 24.0
  soil: null
  tower_height: 30.0
  vegetation: Dry sclerophyll forest
  time_zone: Australia/Sydney
  UTC_offset: 10.0
DalyUncleared:
  id: https://w3id.org/tern/resources/da0668da-cd77-412b-920e-fe334905d406
  fluxnet_id: AU-DaS
  date_commissioned: '2007-02-01'
  latitude: -14.1592
  longitude: 131.3881
  elevation: 110.0
  time_step: 30
  freq_hz: 10
  canopy_height: 16.4
  soil: red kandasol
  tower_height: 21.0
  vegetation: Woody Savanna
  time_zone: Australia/Darwin
  UTC_offset: 9.5
Dookie1:
  id: https://w3id.org/tern/resources/710dbb25-92c9-46b2-8d6f-189a1e7542ad
  fluxnet_id: AU-Do1
  date_commissioned: '2024-10-11'
  latitude: -36.3
  longitude: 145.7
  elevation: 140.0
  time_step: 30
  freq_hz: 10
  canopy_height: null
  soil: null
  tower_height: 3.0
  vegetation: null
  time_zone: Australia/Melbourne
  UTC_offset: 10.0
DryRiver:
  id: https://w3id.org/tern/resources/f4b5f124-8a06-4eef-b4b8-345223856786
  fluxnet_id: AU-Dry
  date_commissioned: '2008-09-01'
  latitude: -15.2588
  longitude: 132.3706
  elevation: 175.0
  time_step: 30
  freq_hz: 10
  canopy_height: 0.15
  soil: red kandasol
  tower_height: 15.0
  vegetation: Woodland savanna
  time_zone: Australia/Darwin
  UTC_offset: 9.5
Fletcherview:
  id: https://w3id.org/tern/resources/d72fe730-721a-43db-8606-fa8ab87f15bd
  fluxnet_id: AU-Fle
  date_commissioned: '2022-01-21'
  latitude: -19.887285
  longitude: 146.189138
  elevation: 260.0
  time_step: 30
  freq_hz: 10
  canopy_height: 12.0
  soil: Black vertisol, cracking clay
  tower_height: 25.0
  vegetation: 'Semi-arid savanna. vegetation1: Reid River Box (Eucalyptus brownii);
    vegetation2: Currant bush (Carissa lanceolata); vegetation3: Perennial Grasses
    (Bothriochloa pertusa dominant).'
  time_zone: Australia/Brisbane
  UTC_offset: 10.0
FrenchIsland:
  id: https://w3id.org/tern/resources/e9906367-7ef4-412a-89aa-554528ec231b
  fluxnet_id: AU-Fre
  date_commissioned: '2019-03-01'
  latitude: -38.3879
  longitude: 145.2783
  elevation: null
  time_step: null
  freq_hz: null
  canopy_height: null
  soil: null
  tower_height: null
  vegetation: null
  time_zone: Australia/Melbourne
  UTC_offset: 10.0
Gingin:
  id: https://w3id.org/tern/resources/85357141-0361-41fe-9708-2c535c50e749
  fluxnet_id: AU-Gin
  date_commissioned: '2011-06-01'
  latitude: -31.3764
  longitude: 115.7139
  elevation: 51.0
  time_step: 30
  freq_hz: 10
  canopy_height: 6.8
  soil: Podosol, Gutless sand
  tower_height: 15.0
  vegetation: Banksia woodland
  time_zone: Australia/Perth
  UTC_offset: 8.0
GreatWesternWoodlands:
  id: https://w3id.org/tern/resources/32400f05-a972-421b-9db1-cde04e8034d9
  fluxnet_id: AU-GWW
  date_commissioned: '2012-12-01'
  latitude: -30.1913
  longitude: 120.6541
  elevation: 385.0
  time_step: 30
  freq_hz: 10
  canopy_height: 18.0
  soil: heavy gravelly red clay
  tower_height: 36.0
  vegetation: sparse eucalypt woodland
  time_zone: Australia/Perth
  UTC_offset: 8.0
HowardSprings:
  id: https://w3id.org/tern/resources/2b9313de-1545-4701-9e5e-ac851f290853
  fluxnet_id: AU-How
  date_commissioned: '2001-08-01'
  latitude: -12.4952
  longitude: 131.15005
  elevation: 64.0
  time_step: 30
  freq_hz: 10
  canopy_height: 16.0
  soil: red kandasol
  tower_height: 23.0
  vegetation: Woody savanna
  time_zone: Australia/Darwin
  UTC_offset: 9.5
Kopuatai:
  id: https://w3id.org/tern/resources/4a9c34f2-4ab8-4034-a78d-95c3f9c6e557
  fluxnet_id: NZ-Kop
  date_commissioned: '2011-11-01'
  latitude: -37.388
  longitude: 175.554
  elevation: null
  time_step: null
  freq_hz: null
  canopy_height: null
  soil: null
  tower_height: null
  vegetation: null
  time_zone: Pacific/Auckland
  UTC_offset: 12.0
Litchfield:
  id: https://w3id.org/tern/resources/1b0227a2-6bbe-4579-9dba-6ee4033e8169
  fluxnet_id: AU-Lit
  date_commissioned: '2015-01-01'
  latitude: -13.17904178
  longitude: 130.7945459
  elevation: 222.0
  time_step: 30
  freq_hz: 10
  canopy_height: 16.0
  soil: red kandasol
  tower_height: 30.0
  vegetation: Woody savanna
  time_zone: Australia/Darwin
  UTC_offset: 9.5
Longreach:
  id: https://w3id.org/tern/resources/9989b745-934a-43c9-b01a-1e7737635c72
  fluxnet_id: AU-Lon
  date_commissioned: '2018-03-01'
  latitude: -23.5233
  longitude: 144.3104
  elevation: 205.346
  time_step: 30
  freq_hz: 10
  canopy_height: 0.5
  soil: Clay
  tower_height: 4.25
  vegetation: Mitchell Grass
  time_zone: Australia/Brisbane
  UTC_offset: 10.0
MyallValeA:
  id: https://w3id.org/tern/resources/8bc01515-8a8c-4c0b-971e-e2b9dad05bd6
  fluxnet_id: AU-MvA
  date_commissioned: '2023-11-14'
  latitude: -30.543
  longitude: 150.02
  elevation: 241.0
  time_step: 30
  freq_hz: 20
  canopy_height: null
  soil: null
  tower_height: null
  vegetation: null
  time_zone: Australia/Sydney
  UTC_offset: 10.0
MyallValeB:
  id: https://w3id.org/tern/resources/12611963-123d-46ca-8a7c-ca6de4d12e8f
  fluxnet_id: AU-MvB
  date_commissioned: '2023-11-17'
  latitude: -30.697
  longitude: 150.09
  elevation: 244.0
  time_step: 30
  freq_hz: 20
  canopy_height: null
  soil: null
  tower_height: null
  vegetation: null
  time_zone: Australia/Sydney
  UTC_offset: 10.0
Oxford:
  id: https://w3id.org/tern/resources/d0c13927-0180-4e55-9509-c0144a9b7f8b
  fluxnet_id: NZ-Oxf
  date_commissioned: '2005-10-01'
  latitude: -43.2619
  longitude: 172.2108
  elevation: null
  time_step: null
  freq_hz: null
  canopy_height: null
  soil: null
  tower_height: null
  vegetation: null
  time_zone: Pacific/Auckland
  UTC_offset: 12.0
Ridgefield:
  id: https://w3id.org/tern/resources/f4da99de-52bd-4041-b6c4-c77b8c9f15ec
  fluxnet_id: AU-Rgf
  date_commissioned: '2015-01-01'
  latitude: -32.5061
  longitude: 116.9668
  elevation: 330.0
  time_step: 30
  freq_hz: 10
  canopy_height: 1.0
  soil: null
  tower_height: 10.0
  vegetation: Wheat
  time_zone: Australia/Perth
  UTC_offset: 8.0
RobsonCreek:
  id: https://w3id.org/tern/resources/a452c22a-d60a-47ea-9f04-01c4407b7d2f
  fluxnet_id: AU-Rob
  date_commissioned: '2013-08-01'
  latitude: -17.1175
  longitude: 145.6301
  elevation: 710.0
  time_step: 30
  freq_hz: 10
  canopy_height: 28.0
  soil: Acidic, Dystrophic, Brown Dermosol
  tower_height: 40.0
  vegetation: Regional Ecosystem (RE) 7.3.36a, complex mesophyll vine forest
  time_zone: Australia/Brisbane
  UTC_offset: 10.0
Samford:
  id: https://w3id.org/tern/resources/c15e9a28-28c4-463f-b164-44b39112d76c
  fluxnet_id: AU-Sam
  date_commissioned: '2010-06-01'
  latitude: -27.3888
  longitude: 152.8725
  elevation: 69.406
  time_step: 30
  freq_hz: 10
  canopy_height: 0.5
  soil: null
  tower_height: 2.0
  vegetation: pasture
  time_zone: Australia/Brisbane
  UTC_offset: 10.0
ScottFarm:
  id: https://w3id.org/tern/resources/fd3263e1-adbf-44eb-9351-58f1ac0659c7
  fluxnet_id: NZ-Sco
  date_commissioned: '2007-12-01'
  latitude: -37.46
  longitude: 175.22
  elevation: null
  time_step: null
  freq_hz: null
  canopy_height: null
  soil: null
  tower_height: null
  vegetation: null
  time_zone: Pacific/Auckland
  UTC_offset: 12.0
SilverPlains:
  id: https://w3id.org/tern/resources/323b884e-52d6-4e58-b212-b7c85cfb874b
  fluxnet_id: AU-Sil
  date_commissioned: '2019-12-01'
  latitude: -42.090556
  longitude: 147.0875
  elevation: 880.0
  time_step: 30
  freq_hz: 10
  canopy_height: 0.1
  soil: Organosol
  tower_height: 2.5
  vegetation: Grass
  time_zone: Australia/Hobart
  UTC_offset: 10.0
SturtPlains:
  id: https://w3id.org/tern/resources/76c37f54-79be-42b5-94e4-6fa015c32cce
  fluxnet_id: AU-Stp
  date_commissioned: '2008-08-01'
  latitude: -17.1507
  longitude: 133.3502
  elevation: 250.0
  time_step: 30
  freq_hz: 10
  canopy_height: 0.5
  soil: red kandasol
  tower_height: 5.0
  vegetation: Mitchell Grasslands
  time_zone: Australia/Darwin
  UTC_offset: 9.5
TiTreeEast:
  id: https://w3id.org/tern/resources/1fa3e3bf-7d9a-448f-b6cd-0830dd4fe0ba
  fluxnet_id: AU-TTE
  date_commissioned: '2012-07-01'
  latitude: -22.287
  longitude: 133.64
  elevation: 553.0
  time_step: 30
  freq_hz: 10
  canopy_height: 6.5
  soil: red kandosol, sandy loam
  tower_height: 13.7
  vegetation: 'Canopy + three types of understorey (vegetation1-4). vegetation1: Mulga
    canopy: Acacia aneura and A. aptaneura; vegetation2: C3 understorey forbs and
    shrubs: Psydrax latifolia, Eremophila gilesii, E. latrobei ssp glabra (Crimson
    turkey bush), Sida and Abutilon spp, and Solanum ellipticum (Potato bush); vegetation3:
    C3 understorey grass: perennial Thyridolepsis mitchelliana (Window mulga-grass);
    vegetation4: C4 understorey grasses: perennial Eragrostis eriopoda (Naked woolybutt)
    and annual Eriachne pulchella ssp pulchella (Pretty wanderrie).'
  time_zone: Australia/Darwin
  UTC_offset: 9.5
Tumbarumba:
  id: https://w3id.org/tern/resources/6b20fe55-0889-4f0a-9e56-2c147f5bd547
  fluxnet_id: AU-Tum
  date_commissioned: '2000-03-01'
  latitude: -35.6566
  longitude: 148.1517
  elevation: 1200.0
  time_step: 60
  freq_hz: 20
  canopy_height: 40.0
  soil: Alfisol
  tower_height: 70.0
  vegetation: wet sclerophyll forest
  time_zone: Australia/Sydney
  UTC_offset: 10.0
Warra:
  id: https://w3id.org/tern/resources/c882ded6-0cb5-493a-939b-fd609706823e
  fluxnet_id: AU-Wrr
  date_commissioned: '2013-03-01'
  latitude: -43.095
  longitude: 146.6545
  elevation: 100.0
  time_step: 30
  freq_hz: 10
  canopy_height: 55.0
  soil: Kurosolic Redoxic Hydrosol
  tower_height: 80.0
  vegetation: Eucalyptus obliqua tall forest
  time_zone: Australia/Hobart
  UTC_offset: 10.0
Wellington:
  id: https://w3id.org/tern/resources/14e4b3d2-9b33-4cc2-a15d-d185fdbc560a
  fluxnet_id: AU-Wel
  date_commissioned: '2023-09-01'
  latitude: -32.57272578
  longitude: 148.9842742
  elevation: 324.0
  time_step: 30
  freq_hz: 10
  canopy_height: null
  soil: null
  tower_height: null
  vegetation: null
  time_zone: Australia/Sydney
  UTC_offset: 10.0
Whroo:
  id: https://w3id.org/tern/resources/b512e2dc-98a6-40d5-a91c-ad8f47d1ace7
  fluxnet_id: AU-Whr
  date_commissioned: '2011-10-01'
  latitude: -36.6732
  longitude: 145.0294
  elevation: 165.0
  time_step: 30
  freq_hz: 10
  canopy_height: 28.0
  soil: null
  tower_height: 35.0
  vegetation: Dry sclerophyll woodland
  time_zone: Australia/Melbourne
  UTC_offset: 10.0
WombatStateForest2:
  id: https://w3id.org/tern/resources/bf3daf01-0e7a-4e18-aa9d-460be3fe06cc
  fluxnet_id: AU-Wom
  date_commissioned: NaT
  latitude: null
  longitude: null
  elevation: null
  time_step: 30
  freq_hz: 10
  canopy_height: Ask Cacilia/Stefan
  soil: silt-clay/clay
  tower_height: 40.19
  vegetation: dry sclerophyll eucalypt forest
  time_zone: null
  UTC_offset: null
Yanco:
  id: https://w3id.org/tern/resources/eba13c16-2dac-49ba-b8f4-fed55b8657ab
  fluxnet_id: AU-Ync
  date_commissioned: '2012-04-01'
  latitude: -34.9878
  longitude: 146.2908
  elevation: 126.0
  time_step: 30
  freq_hz: 10
  canopy_height: 0.5
  soil: sandy loams, scattered clays, red brown earths, deep sands
  tower_height: 20.0
  vegetation: Pasture
  time_zone: Australia/Sydney
  UTC_offset: 10.0
YarramundiControl:
  id: https://w3id.org/tern/resources/304f1968-1a8a-4acb-a8ab-283a9bea9338
  fluxnet_id: AU-Ya1
  date_commissioned: NaT
  latitude: -33.613469
  longitude: 150.734864
  elevation: 30.0
  time_step: null
  freq_hz: null
  canopy_height: 0.5
  soil: null
  tower_height: 2.0
  vegetation: pasture, unirrigated
  time_zone: Australia/Sydney
  UTC_offset: 10.0
YarramundiIrrigation:
  id: https://w3id.org/tern/resources/589c42b2-7d94-4ebc-b4c7-54b815dc1312
  fluxnet_id: AU-Ya2
  date_commissioned: NaT
  latitude: -33.620812
  longitude: 150.763284
  elevation: 30.0
  time_step: null
  freq_hz: null
  canopy_height: 0.5
  soil: null
  tower_height: 2.0
  vegetation: pasture, irrigated
  time_zone: Australia/Sydney
  UTC_offset: 10.0
